---
title: "Syllabus"
output: pdf_document
---

## PSYC 3435 - Principles of Research for the Behavioral Sciences

- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MTWRF 1:30-3:00 pm; TR 10:00-11:30 am
- Email: faulkenberry@tarleton.edu
- Twitter: [tomfaulkenberry](http://twitter.com/tomfaulkenberry)
- Web: [tomfaulkenberry.github.io](http://tomfaulkenberry.github.io)
- Phone: 254-968-9816

## Course description

This laboratory course is designed to introduce students to the philosophy of scientific inquiry with an emphasis on experimental methodology. This will be accomplished via a combination of traditional lectures along with an application of principles through laboratory experimentation and demonstration. Essentially, we will cover the "nuts and bolts" of putting together and completing a research project in psychology. To this end, we will cover all fourteen chapters of the textbook. All students enrolled in this course are required to have **previously taken** PSYC 3309 (Writing in Psychology) and PSYC 3330 (Statistics). 

## Course materials

- The Process of Research in Psychology (2nd ed.) by McBride (2013) [(Amazon link)](http://www.amazon.com/Process-Research-Psychology-Dawn-McBride/dp/1412999553/)
- APA Publication Manual (6th ed.) [(Amazon link)](http://www.amazon.com/Publication-Manual-American-Psychological-Association/dp/1433805618/)
- JASP statistical software (free download from [jasp-stats.org](http://jasp-stats.org))
- In addition, you will need to obtain the following articles from PsycInfo:
    - Derks, B., Van Laar, C., Elmers, N., & de Groot, K. (2011). Gender-bias primes elicit queen-bee responses among senior policewomen. *Psychological Science, 22*, 1237-1242.
    - John, L. K., Loewenstein, G., & Prelec, D. (2012). Measuring the prevalence of questionable research practices with incentives for truth telling. *Psychological Science, 23*, 524-532.
    - Mueller, J. S., Melwani, S., & Goncalo, J. A. (2012). The bias against creativity: Why people desire but reject creative ideas. *Psychological Science, 23*, 13-17.
    - Slepian, M. L., Weisbuch, M., Rule, N. O, & Ambady, N. (2011). Tough and tender: Embodied categorization of gender. *Psychological Science, 22*, 26-28.
    - Topolinski, S. (2011). I 5683 You: Dialing phone numbers on cell phones activates key-concordant concepts. *Psychological Science, 22*, 355-360.

## Student learning outcomes

1.  Describe advantages of the scientific method compared to other approaches
2.	Identify various research designs and uses of each
3.	Conduct library research
4.	Paraphrase and cite material from primary sources 
5.	Develop a research question and write hypotheses appropriate for it
6.	Design and conduct a research project to test hypotheses
7.	Analyze data collected from research using computer software
8.	Communicate the findings of research as a complete APA style manuscript


## Requirements and grading

- Exam 1 (100 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (150 pts)
- Weekly quizzes (100 pts)
- Lab assignments (100 pts)
- Research participation (50 pts)
- *Total = 700 points*

Grades will be assigned based on the percentage of points you accumulate out of these 700 points.  I will use the standard grading scale of A=90%, B=80%, etc.

### Exams (64% of grade)

There will be four exams throughout the semester.  They will cover material from the text and the lectures.  Exam questions will be a mix of multiple choice and short answer and will be worth 100 points each.

Dates:

- Exam 1 (Wednesday, Feb 10)
- Exam 2 (Wednesday, March 23)
- Exam 3 (Wednesday, April 20)
- Final exam (Monday, May 2, 3:00-5:30 pm)

### Unit quizzes (14% of grade)

Every Friday (excluding exam weeks), there will be a short in-class quiz over the material covered in lectures on Monday and Wednesday. Typically, the quizzes will consist of multiple choice questions, although the format may change occasionally depending on material.  Your final quiz average will be scaled to a total of 100 points for the semester (i.e., if you average 8.6/10 points over all quizzes, your final quiz grade will be 86/100).

### Lab assignments (14% of grade)

There will be four lab assignments this semester.  Each assignment is designed to give you first hand experience with essential research skills, such as conducting an experiment, collecting data, and writing up an APA manuscript.  Except for Lab 1 (an APA exercise), each of you will administer a short experiment, collect some data, analyze the collected data for the class, and compose an APA manuscript based on the experiment and the results. 

Lab Assignments and dates

- Lab 1 – APA formatting (10 points), due Friday, Feb 12
- Lab 2.1 – Correlational design, data collection (10 points), due Friday, Feb 19
- Lab 2.2 – Correlational design, analysis and report (20 points), due Friday, Mar 4
- Lab 3.1 – Independent groups design, data collection (10 points), due Friday, Mar 25
- Lab 3.2 – Independent groups design, analysis and report (20 pts.), due Friday, Apr 8
- Lab 4.1 – Factorial design, data collection (10 points), due Friday, Apr 15
- Lab 4.2 – Factorial design, analysis and report (20 points), due Friday, Apr 29

## Research participation (8% of grade)

Research is the lifeblood of psychology!  In order to promote your growth as a psychological scientist, you will be required to participate in 2 "units" of research over the course of the semester.  Roughly defined, a "unit" of research consists of either (1) participation in one hour of psychological experiments, usually offered right here in the Psychology department at Tarleton, or (2) a 3-5 page critical reflection of an empirical research article related to human learning and/or cognition, usually chosen by me.  Instructions for participation will be given in class.


## Course Communication

I am your primary resource for this course. I AM an experimental psychologist, so I do the stuff I teach about daily. Hence, my primary interest is for you to learn this material and do well in the course. You may contact me using any means necessary (email and Twitter are the best). That being said, many people prefer to use Blackboard messages. I don’t mind these, but keep in mind that I may not receive your message until I actually open Blackboard. With email/Twitter, if you send me a message at 9:00 pm, I may actually respond pretty quickly. 

## University Policy on "F" Grades

Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

## Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

## Tarleton's Spring Service Week

In support of Tarleton’s core value of service, each student is expected to participate in a service learning experience as a part of the Spring term week of service (April 4-8).  This experience will challenge students to be engaged in the local community, address a community need, connect course objectives to the world around you, and involve structured student reflection. In this service learning experience you will not only enhance your knowledge and skills, but actively use those skills as you serve your community.

## Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act (ADA) and other federal, state, and local laws relative to the provision of disability services. Students with disabilities attending Tarleton State University may contact the Office of Disability Services at (254) 968-9478 to request appropriate accommodation. Furthermore, formal accommodation requests cannot be made until the student has been officially admitted to Tarleton State University.


**Note:  any changes to this syllabus will be communicated to you by the instructor!**

## Semester schedule

Week | Dates    | Lecture (MW)           | Workshop (F)
---- | -------- | -----------------------| -----------------------
1 | Jan 11-15 | Knowing in psychological science (Ch 1) | Discuss Mueller et al. (2012)
2 | Jan 18-22 | Reading the literature / APA style (Ch 2,8) | Intro to Lab 1: APA formatting in Word
3 | Jan 25-29 | Basic research methods (Ch 3) | Discuss Slepian et al. (2011)
4 | Feb 1-5 | Ethics in psychological science (Ch 5) | Discuss John et al. (2012) 
5 | Feb 8-12 | **Exam 1** | Intro to Lab 2: correlational designs 
6 | Feb 15-19 | Experiments: selecting and manipulating variables (Ch 4) | Lab 2: correlations in JASP 
7 | Feb 22-26 | Experiments: sampling methods (Ch 6) | Discuss Topolinski (2011) 
8 | Feb 29-Mar 4 | Experiments: basic designs (Ch 11) | TBA
- | Mar 7-11 | - | *Spring break!* | -
9 | Mar 14-18 | Experiments: factorial designs (Ch 11) | Intro to Lab 3: independent groups designs
10 | Mar 21-25 | **Exam 2** | Lab 3: $t$-tests in JASP 
11 | Mar 28-Apr 1 | Non-experiments: survey methods (Ch 9) | TBA
12 | Apr 4-8 | Non-experiments: correlational designs (Ch 10) | No class: SWPA
13 | Apr 11-15 | Non-experiments: quasi-experiments and developmental designs (Ch 12,13) | Introduce Lab 4: factorial designs 
14 | Apr 18-22 | **Exam 3** | Lab 4: factorial ANOVA in JASP
15 | Apr 25-29 | Course review | -
16 | May 2-6 | **Final exam** | -