#+TITLE: 
#+AUTHOR:
#+OPTIONS: toc:nil num:nil
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [article,10pt]
#+LATEX_HEADER: \usepackage[left=1in,right=1in,bottom=1in,top=1in]{geometry}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancyplain}
#+LATEX_HEADER: \lfoot{Last updated \today} \cfoot{} \rfoot{\thepage}

* Thomas J. Faulkenberry, Ph.D.

Department of Psychological Sciences\\  
Tarleton State University\\
Box T-0820, Stephenville, TX 76402\\  
Phone: +1 (254) 968-9816\\  
Email: faulkenberry@tarleton.edu\\
Website: [[http://tomfaulkenberry.github.io]]

** Education   
- Ph.D., Psychology, Texas A&M University – Commerce, 2010
- M.S., Mathematics, Oklahoma State University - 2002
- B.S. with highest honors, Mathematics, Southeastern Oklahoma State University, 2000

** Academic positions
- 2019-present: Associate Professor (with tenure), Department of Psychological Sciences, Tarleton State University
- 2013-2019: Assistant Professor, Department of Psychological Sciences, Tarleton State University
- 2012-2013: Assistant Professor, Department of Mathematics, Texas A&M University – Commerce
- 2010-2012: Visiting Assistant Professor, Department of Psychology and Special Education, Texas A&M University – Commerce
- 2005-2010: Lecturer, Department of Mathematics, Texas A&M University - Commerce

** Honors and awards
- O. A. Grant Excellence in Teaching Award, Tarleton State University College of Education, 2018
- Faculty Excellence in Scholarship Award, Tarleton State University College of Education, 2016
- President's All-Purple Award, Tarleton State University, 2016
- Nominee, Bruce N. Chaloux Award for Early Career Excellence in Online Education, Sloan Consortium, 2015
- Fellow, The Psychonomic Society, 2014
- Texas A&M University System Teaching Excellence Award, 2010-2011
- Best Graduate Student Presentation, Annual Research Symposium, TAMU-C, 2010
- O.H. Hamilton Fellowship in Mathematics, Oklahoma State University, 2002
- S. J. Scroggs Distinguished Graduate Fellowship, Oklahoma State University, 2001
- Regional University Scholarship (4 years), Southeastern Oklahoma State University, 1996
  
** Administrative activities
- 2019-present: Assistant Head, Department of Psychological Sciences, Tarleton State University
- 2011-2012: Director, Center for Undergraduate Research and Creative Activities, TAMU-C
- 2010-2011: Director, Math & Science Teacher Preparation Program (LeoTEACH), TAMU-C

** Research publications
1. Faulkenberry, T. J., Ly, A., & Wagenmakers, E. J. (in press). Bayesian statistics in numerical cognition: A tutorial using JASP. To appear in /Journal of Numerical Cognition/. https://psyarxiv.com/vg9pw/
1. Faulkenberry, T. J. (in press). Estimating Bayes factors from minimal ANOVA summaries for repeated-measures designs. To appear in /Metodoloski Zvezki: Advances in Methodology and Statistics/. https://arxiv.org/abs/1905.05569
1. Nejman, J. A. & Faulkenberry, T. J. (in press). Implicit priming reveals decomposed processing in fraction comparison. To appear in /Journal of Psychological Inquiry/. https://psyarxiv.com/nkw45/
1. Faulkenberry, T. J., Cruise, A., & Shaki, S. (2020). Task instructions modulate unit-decade binding in two-digit number representation. /Psychological Research/, /84/, 424-439. doi: [[https://dx.doi.org/10.1007/s00426-018-1057-9][10.1007/s00426-018-1057-9]]
2. Faulkenberry, T. J. (2019). Estimating evidential value from ANOVA summaries: A comment on Ly et al. (2018). /Advances in Methods and Practices in Psychological Science/, /2/, 406-409. doi: [[https://doi.org/10.1177/2515245919872960][10.1177/2515245919872960]]
3. Faulkenberry, T. J. (2019). A tutorial on generalizing the default Bayesian t-test via posterior sampling and encompassing priors. /Communications for Statistical Applications and Methods/, /26/, 217-238. doi: [[https://doi.org/10.29220/CSAM.2019.26.2.217][10.29220/CSAM.2019.26.2.217]]
4. Frampton, A. R., & Faulkenberry, T. J. (2018). Mental arithmetic processes: Testing the independence of encoding and calculation. /Journal of Psychological Inquiry/, /22/, 30-35. https://www.psychinquiry.org/wp-content/uploads/2019/03/Vol22-1.pdf
5. Faulkenberry, T. J., Vick, A. D., & Bowman, K. A. (2018). A shifted Wald decomposition of the numerical size-congruity effect: Support for a late interaction account. /Polish Psychological Bulletin/, /49/, 391-397. doi: [[http://dx.doi.org/10.24425/119507][10.24425/119507]]
6. Faulkenberry, T. J., Witte, M., & Hartmann, M. (2018). Tracking the continuous dynamics of numerical processing: A brief review and editorial. /Journal of Numerical Cognition/, /4/(2), 271-285. doi: [[http://dx.doi.org/10.5964/jnc.v4i2.179][10.5964/jnc.v4i2.179]]
7. Faulkenberry, T. J. (2018). Computing Bayes factors to measure evidence from experiments: An extension of the BIC approximation. /Biometrical Letters/, /55/(1), 31-43. doi: [[https://doi.org/10.2478/bile-2018-0003][10.2478/bile-2018-0003]]
8. Faulkenberry, T. J. (2018). A simple method for teaching Bayesian hypothesis testing in the brain and behavioral sciences. /Journal of Undergraduate Neuroscience Education/, /16/, A126-A130. http://www.funjournal.org/wp-content/uploads/2018/01/june-16-126.pdf?x91298
9. Faulkenberry, T. J. (2017). A single-boundary accumulator model of response times in an arithmetic verification task. /Frontiers in Psychology/, /8:1225/. doi: [[http://dx.doi.org/10.3389/fpsyg.2017.01225][10.3389/fpsyg.2017.01225/]]
10. Faulkenberry, T. J., Cruise, A., & Shaki, S. (2017). Reversing the manual digit bias in two-digit number comparison. /Experimental Psychology/, /64/, 191-204.  doi: [[http://dx.doi.org/10.1027/1618-3169/a000365][10.1027/1618-3169/a000365]]
11. Sobel, K. V., Puri, A. M., Faulkenberry, T. J., & Dague, T. D. (2017). Visual search for conjunctions of physical and numerical size shows that they are processed independently. /Journal of Experimental Psychology: Human Perception & Performance/, /43/, 444-453. doi: [[http://dx.doi.org/10.1037/xhp0000323][10.1037/xhp0000323]]
12. Faulkenberry, T. J., & Tummolini, L. (2016). Commentary: Is there any Influence of Variations in Context on Object-Affordance Effects in Schizophrenia? Perception of Property and Goals of Action). /Frontiers in Psychology/, /7:1915/. doi: [[http://dx.doi.org/10.3389/fpsyg.2016.01915][10.3389/fpsyg.2016.01915]]
13. Faulkenberry, T. J. (2016). Testing a direct mapping versus competition account of response dynamics in number comparison. /Journal of Cognitive Psychology/, /28/, 825-842. doi: [[http://dx.doi.org/10.1080/20445911.2016.1191504][10.1080/20445911.2016.1191504]]
14. Sobel, K. V., Puri, A. M., & Faulkenberry, T. J. (2016). Bottom-up and top-down attentional contributions to the size-congruity effect. /Attention, Perception, & Psychophysics/, /78/, 1324-1336. doi: [[http://dx.doi.org/10.3758/s13414-016-1098-3][10.3758/s13414-016-1098-3]]
15. Faulkenberry, T. J., Cruise, A., Lavro, D., & Shaki, S. (2016). Response trajectories capture the continuous dynamics of the size congruity effect. /Acta Psychologica/, /163/, 114-123. doi: [[http://dx.doi.org/10.1016/j.actpsy.2015.11.010][10.1016/j.actpsy.2015.11.010]]
16. Faulkenberry, T. J., Montgomery, S. A., & Tennes, S. N. (2015). Response trajectories reveal the temporal dynamics of fraction representations. /Acta Psychologica/, /159/, 100-107. doi: [[http://dx.doi.org/10.1016/j.actpsy.2015.05.013][10.1016/j.actpsy.2015.05.013]]
17. Faulkenberry, T. J., & Rey, A. R. (2014). Extending the reach of mousetracking in numerical cognition: A comment on Fischer and Hartmann (2014). /Frontiers in Psychology/, /5/:1436. doi: [[http://dx.doi.org/10.3389/fpsyg.2014.01436][10.3389/fpsyg.2014.01436]]
18. Faulkenberry, T. J. (2014). Hand movements reflect competitive processing in numerical cognition. /Canadian Journal of Experimental Psychology/, /68/, 147-151. doi: [[http://dx.doi.org/10.1037/cep0000021][10.1037/cep0000021]]
19. Faulkenberry, T. J., & Geye, T. L. (2014). The cognitive origins of mathematics learning disability: A review. /The Rehabilitation Professional/, /22/ (1), 9-16.
20. Faulkenberry, T. J., & Faulkenberry, E. D. (2013). Teaching integer arithmetic without rules: An embodied approach. /Oklahoma Journal of School Mathematics/, /5/ (2), 5-14.
21. Faulkenberry, T. J., (2013). The conceptual/procedural distinction belongs to strategies, not tasks: A comment on Gabriel et al. (2013). /Frontiers in Psychology/, /4/:820. doi: [[http://dx.doi.org/10.3389/fpsyg.2013.00820][10.3389/fpsyg.2013.00820]]
22. Faulkenberry, T. J., & Montgomery, S. A. (2013). The primacy of fraction components in adults’ numerical judgements. In Reeder, S. L. and Matney, G. T. (Eds.). /Proceedings of the 40th Annual Meeting of the Research Council on Mathematics Learning/ (pp. 155-162). Tulsa, OK: RCML
23. Faulkenberry, T. J. (2013). How the hand mirrors the mind: The embodiment of numerical cognition. In Reeder, S. L. and Matney, G. T. (Eds.). /Proceedings of the 40th Annual Meeting of the Research Council on Mathematics Learning/ (pp. 205-212). Tulsa, OK: RCML
24. Faulkenberry, E. D., & Faulkenberry, T. J. (2012). Do you see what I see? An exploration of self-perception in the classroom. In S. L. Reeder (Ed.), /Proceedings of the 39th Annual Meeting of the Research Council on Mathematics Learning/ (pp. 121-126). Charlotte, NC: RCML.
25. Faulkenberry, T. J., & Pierce, B. H. (2011). Mental representations in fraction comparison: Holistic versus component-based strategies. /Experimental Psychology/, /58/, 480-489. doi: [[http://dx.doi.org/10.1027/1618-3169/a000116][10.1027/1618-3169/a000116]]
26. Faulkenberry, T. J. (2011). Individual differences in mental representations of fraction magnitude. In S. Reeder (Ed.) /Proceedings of the 38th Annual Meeting of the Research Council on Mathematics Learning/ (pp. 136-143). Cincinnati, OH: RCML.
27. Faulkenberry, E. D., & Faulkenberry, T. J. (2010). Transforming the way we teach function transformations. /Mathematics Teacher/, /104/, 29-33.
28. Faulkenberry, T. J. (2010). The working memory demands of simple fraction strate- gies. In S. Reeder (Ed.) /Proceedings of the 37th Annual Meeting of the Research Council on Mathematics Learning/ (pp. 84-89). Conway, AR: RCML.
29. Faulkenberry, E. D. & Faulkenberry, T. J. (2006). Constructivism in mathematics education: A historical and personal perspective. /The Texas Science Teacher/, /35/, 17- 22.
    
** Abstracts, columns, and book reviews
1. Faulkenberry, T. J. (2020). Statistics education awards presented at Joint Mathematics Meetings. /MAA Focus/, /40(2)/, 40. https://www.maa.org/press/periodicals/maa-focus
1. Faulkenberry, T. J. (2020). Closed form Bayes factor techniques for measuring evidential value from analysis of variance models. /Abstracts of Papers Presented to the American Mathematical Society./, /41/, 256.
1. Faulkenberry, T. J. (2019). Book review of "Handbook of Approximate Bayesian Computation". /MAA Reviews/, https://www.maa.org/press/maa-reviews/handbook-of-approximate-bayesian-computation.
1. Bowman, K. A., & Faulkenberry, T. J. (2019). Response time modeling supports a late interaction account of the size-congruity effect. /Abstracts of the Psychonomic Society/, /24/, 227-228.
1. Faulkenberry, T. J. (2019). Treasurer's Column: Financial Challenges in Albuquerque. /Southwestern Psychologist/, /12(2)/, 3. 
1. Faulkenberry, T. J. (2018). Modeling individual difference structures in the size-congruity effect. /Abstracts of the Psychonomic Society/, /23/, 42.
1. Bowman, K. A., & Faulkenberry, T. J. (2018). Nonwords induce reverse priming effects in a lexical decision task. /Abstracts of the Psychonomic Society/, /23/, 246.
1. Faulkenberry, T. J. (2018). Treasurer's Column: Where does the money go? A quick picture of SWPA finances. /Southwestern Psychologist/, /11(1)/, 3.
1. Faulkenberry, T. J. (2017). A single-boundary accumulator model of decisions in a mental arithmetic task. /Abstracts of the Psychonomic Society/, /22/, 27.
1. Geye, T. L., & Faulkenberry, T. J. (2017). Computer mousetracking reveals the facilitation and interference components of the size congruity effect. /Abstracts of the Psychonomic Society/, /22/, 106.
1. Bowman, K. A., & Faulkenberry, T. J. (2017). The dynamics of spatial-operational momentum in mental arithmetic. /Abstracts of the Psychonomic Society/, /22/, 188.
1. Faulkenberry, T. J. (2017). Treasurer's Column: Standing on the shoulders of giants. /Southwestern Psychologist/, /10(2)/, 5.
1. Faulkenberry, T. J. (2016). Motor dynamics support a competition model of number processing. /Abstracts of the Psychonomic Society/, /21/, 26.
1. Bowman, K. A., & Faulkenberry, T. J. (2016). Testing competing models of two-digit number representation: Decomposed versus holistic processing. /Abstracts of the Psychonomic Society/, /21/, 285. 
1. Faulkenberry, T. J. (2016). Decoding the development of mathematical thinking: A book review of /Development of Mathematical Thinking: Neural Substrates and Genetic Influences/. /PsycCRITIQUES/, /61/ (31). doi: [[http://dx.doi.org/10.1037/a0040434][10.1037/a0040434]]
1. Faulkenberry, T. J. (2016). Undergraduate students: An endangered resource? /Southwestern Psychologist/, /9(1)/, 2.
1. Faulkenberry, T. J., Cruise, A., Lavro, D., & Shaki, S. (2015). Response trajectories support a late-interaction model of the size-congruity effect. /Canadian Journal of Experimental Psychology, 69/, 346.
1. Faulkenberry, T. J., Cruise, A., & Shaki, S. (2015). Reversing the manual decade bias in two-digit number comparison. /Abstracts of the Psychonomic Society, 20/, 39.
1. Geye, T. L, & Faulkenberry, T. J. (2015). Response trajectories capture individual differences in a size congruity task. /Abstracts of the Psychonomic Society, 20/, 249.
1. Faulkenberry, T. J., Cruise, A., Lavro, D., & Shaki, S. (2014). Response trajectories capture the continuous dynamics of the size-congruity effect. /Abstracts of the Psychonomic Society, 19/, 53.
1. Faulkenberry, T. J. (2013). Measuring the working memory requirements of mental arithmetic. /Canadian Journal of Experimental Psychology, 67/, 281.
1. Faulkenberry, T. J. (2013). Measuring the working memory requirements of mental arithmetic. /Abstracts of the Psychonomic Society, 18/, 203-204.
1. Faulkenberry, T. J. (2012). The temporal dynamics of fraction representations: Components are processed first. /Canadian Journal of Experimental Psychology, 66/, 310.
1. Faulkenberry, T. J. & Montgomery, S. A. (2012). The primacy of components in numerical fractions. /Abstracts of the Psychonomic Society, 17/, 206.
1. Faulkenberry, T. J. (2011). Brain-based mathematics: Promising practice or hopeful hype? /RCML Intersection Points, 35/ (3), 9-10.
1. Faulkenberry, T. J. & Kelsey, A. R. (2011). Working memory and strategic performance in fraction comparison. /Canadian Journal of Experimental Psychology, 65/, 311-311.
1. Faulkenberry, T. J. (2011). The dynamics of the SNARC effect: Evidence from mouse tracking. /Canadian Journal of Experimental Psychology, 65/, 316-316.
1. Faulkenberry, T. J. (2011). Motor dynamics in numerical representations: Evidence from mouse tracking. /Abstracts of the Psychonomic Society, 16/, 76-76.
1. Faulkenberry, T. J. (2010). The roles of phonological and visuo-spatial working memory resources in simple fraction strategies. /Canadian Journal of Experimental Psychology, 64/, 302-302.
1. Lu, S. Wakefield, L. & Faulkenberry, T. J. (2006). The roles of beginnings, overlap, and ends in event temporal relations. /Abstracts of the Psychonomic Society, 11/, 9-9.

** Conference Presentations
1. Faulkenberry, T. J. (June 2020). A systems factorial technology approach to classifying the architecture of fraction perception. Math Cognition and Learning Society, Dublin, Ireland (cancelled due to COVID-19)
1. Scheuler, B., & Faulkenberry, T. J. (April 2020). An illustration of Bayesian hypothesis testing: The case of the facial feedback effect. Southwestern Psychological Association, Frisco, TX (cancelled due to COVID-19)
1. Faulkenberry, T. J. (April 2020). Getting started with Bayesian inference in psychology: A workshop using JASP. Southwestern Psychological Association, Frisco, TX (cancelled due to COVID-19)
1. Bowman, K., Caldwell, K., Garcia, B., & Faulkenberry, T. J. (April 2020). Maximum likelihood estimation of the Ex-Gaussian model for response time distributions. Southwestern Psychological Association, Frisco, TX (cancelled due to COVID-19)
1. Faulkenberry, T. J., (November, 2019). Org-mode and FoilTeX - an unlikely (but useful) combination for teaching", EmacsConf2019, Free Software Foundation, Virtual / Online.
1. Faulkenberry, T. J. (June, 2019). A hierarchical Bayesian model of individual difference structures for the size-congruity effect. Math Cognition and Learning Society, Ottawa, ON.
1. Faulkenberry, T. J., Hetzel, S., & Bowman, K. (April, 2019). A systems factorial technology approach to classifying the architecture of fraction perception. Southwestern Psychological Association, Albuquerque, NM.
1. Faulkenberry, T. J. (April, 2019). An introduction to the theory and practice of Bayesian hypothesis testing: A workshop using JASP. Southwestern Psychological Association, Albuquerque, NM.
1. Bowman, K., & Faulkenberry, T. J. (April, 2019). Response time modeling supports a late interaction account of the size-congruity effect. Southwestern Psychological Association, Albuquerque, NM.
1. Faulkenberry, T. J. (January, 2019). Demonstrating Bayesian model comparison with a class-sourced experiment in mental arithmetic. National Institute on the Teaching of Psychology (NITOP), St. Pete Beach, FL 
1. Faulkenberry, T. J. (April, 2018). Introduction to Bayesian inference for the psychological sciences (workshop). Southwestern Psychological Association, Houston, TX
1. Bowman, K. A., & Faulkenberry, T. J. (April, 2018). The dynamics of spatial operational momentum in mental arithmetic. Southwestern Psychological Association, Houston, TX.
1. Faulkenberry, T. J. (November, 2017). A hierarchical Bayesian model for measuring response times in a mental arithmetic task. Society for Mathematical Psychology, Vancouver, BC.
1. Faulkenberry, T. J. (April, 2017). Accumulator models of decision processes in mental arithmetic. Southwestern Psychological Association, San Antonio, TX
1. Faulkenberry, T. J., & Wood, J. (April, 2017). A Bayesian perspective on the operator preview paradigm in mental arithmetic. Southwestern Psychological Association, San Antonio, TX
1. Nejman, J., & Faulkenberry, T. J. (April, 2017). Implicit priming reveals both holistic and decomposed processing in fraction comparison. Southwestern Psychological Association, San Antonio, TX
1. Wood, J., & Faulkenberry, T. J. (April, 2017). The dynamics of operator preview effects in mental arithmetic. Southwestern Psychological Association, San Antonio, TX
1. Bowman, K., & Faulkenberry, T. J. (April, 2017). Testing competing models of two-digit number representation: Decomposed versus holistic processing. Southwestern Psychological Association, San Antonio, TX
1. Faulkenberry, T. J. (April, 2016). Testing two accounts of response dynamics in a number comparison task. Southwestern Psychological Association, Dallas, TX
1. Faulkenberry, T. J. (April, 2016). Recent developments on the size congruity effect in numerical cognition. Southwestern Psychological Association, Dallas, TX
1. Rutledge, M., & Faulkenberry, T. J. (April, 2016). Spatial-numerical associations in mental arithmetic. Southwestern Psychological Association, Dallas, TX
1. Geye, T., & Faulkenberry, T. J. (April, 2016). Computer mousetracking reveals individual differences in a size congruity task. Southwestern Psychological Association, Dallas, TX
1. Bowman, K. A., & Faulkenberry, T. J. (April, 2016). The effects of mathematical fluency on multi-digit number representations. Southwestern Psychological Association, Dallas, TX
1. Faulkenberry, T. J. (October, 2015). Testing a direct-mapping versus competition account of response dynamics in a number comparison task. ARMADILLO 2015, Waco, TX.
1. Bowman, K. A., & Faulkenberry, T. J. (October, 2015). The effects of mathematical fluency on multi-digit number representations. ARMADILLO 2015, Waco, TX.
1. Bowman, K. A., & Faulkenberry, T. J. (October, 2015). The effects of mathematical fluency on multi-digit number representations. TAMUS Pathways Symposium, Corpus Christi, TX.
1. Bowman, K. A., & Faulkenberry, T. J. (October, 2015). The effects of mathematical fluency on multi-digit number representations. Tarleton Research Symposium, Stephenville, TX.
1. Faulkenberry, T. J. (April, 2015). Class-sourcing replications of reaction time studies: An example in mathematical cognition. Southwestern Teachers of Psychology Conference, Wichita, KS.
1. Geye, T., Fleming, B., & Faulkenberry, T. J. (April, 2015). Validation of the calculation fluency test for measuring arithmetic skills. Southwestern Psychological Association, Wichita, KS.
1. Frampton, A., & Faulkenberry, T. J. (April, 2015). Cognitive arithmetic processs: The effects of problem size and format on performance. Southwestern Psychological Association, Wichita, KS.
1. Faulkenberry, T. J. (April, 2015). Evidence for a late-interactions model of the numerical size congruity effect. Southwestern Psychological Association, Wichita, KS.
1. Harris Bozer, A., & Faulkenberry, T. J. (April, 2015). Applying the CREATE pedagogical tool to the online animal behavior course to enhance scientific literacy.  2015 CIRTL Forum: Preparing the Future STEM Faculty for the Rapidly Changing Landscape of Higher Education, College Station, TX.
1. Frampton, A., & Faulkenberry, T. J. (March, 2015). Cognitive arithmetic processes: The effects of numerical surface form on strategy choice. Texas Undergraduate Research Day at the Capitol, Austin, TX.
1. Faulkenberry, E. D., Smith, K., Riggs, E., & Faulkenberry, T. J. (February, 2015). The evolution of PST’s beliefs: Examining the effect of teacher preparation. Research Council on Mathematics Learning, Las Vegas, NV.
1. Faulkenberry, T. J. (October, 2014).  Hand movements reflect competitive processing in a numerical parity task. ARMADILLO 2014, Norman, OK.
1. Faulkenberry, T. J. (October, 2014). The dynamics of fraction representations: Components are processed first. ARMADILLO 2014, Norman, OK.
1. Faulkenberry, T. J. (April, 2014). Hand movements reflect competitive processing in numerical fraction representations. Southwestern Psychological Association, San Antonio, TX.
1. Faulkenberry, T. J. (April, 2014). A brief introduction to using R for teaching statistical methods. Southwestern Teachers of Psychology Conference, San Antonio, TX.
1. Faulkenberry, T. J. (March, 2014). A classroom activity for demonstrating confirmation bias. Tarleton Excellence in Teaching Conference, Stephenville, TX.
1. Smith, K. H., Riggs, B., Faulkenberry, E. D., & Faulkenberry, T. J. (February, 2014). A snapshot of preservice teacher beliefs: A factor analytic method. Research Council on Mathematics Learning, San Antonio, TX.
1. Faulkenberry, T. J. (April, 2013). Modeling the roles of working memory and strategy type in fraction comparison. TX Section MAA Meeting, Texas Tech University, Lubbock, TX.
1. Faulkenberry, T. J. (March, 2013). Estimating the working memory requirements of mental arithmetic. OK-AR Section MAA Meeting, Oklahoma State University, Stillwater, OK.
1. Faulkenberry, T. J. (April, 2012). Some limitations in measuring working memory capacity. TX Section MAA Meeting, El Centro College, Dallas, TX.
1. Faulkenberry, T. J. (February, 2012). Examining the role of testing in learning mathematics: Directions for future research. 39th Annual Meeting of the Research Council on Mathematics Learning, Charlotte, NC.
1. Faulkenberry, T. J. & Pierce, B. H. (October, 2011). The roles of working memory and strategy type in fraction comparison. ARMADILLO 2011, Commerce, TX.
1. Faulkenberry, T. J. (April, 2010). Working memory and strategy execution in simple fraction strategies. Annual Research Symposium, Texas A& M University - Commerce.
1. Faulkenberry, T. J. (April, 2009). Mathematics anxiety among elementary education majors: Does test format matter?. Annual Research Symposium, Texas A& M University - Commerce.
1. Faulkenberry, T. J. (February, 2009). Mathematics anxiety among elementary education majors. 36th Annual Meeting of the Research Council on Mathematics Learning, Rome, GA.
1. Faulkenberry, E. D. & Faulkenberry, T. J. (February, 2008). An assessment of the mathematical knowledge of elementary preservice teachers with regard to number and operation. 35th Annual Meeting of the Research Council on Mathematics Learning, Oklahoma City, OK.
1. Faulkenberry, T. J. (February, 2008). Working memory: Cognitive and instructional implications for mathematics. 35th Annual Meeting of the Research Council on Mathematics Learning, Oklahoma City, OK.
1. Faulkenberry, E. D. & Faulkenberry, T. J. (October, 2005). Using the geometry module in Teacher Quality grants. Charles A. Dana Center Higher Education Mathematics Conference, Austin, TX.
1. Faulkenberry, T. J. (April, 2005). Cognitive frameworks in advanced mathematical thinking. MAA Texas Section Meeting, University of Texas - Arlington.
1. Faulkenberry, T. J. (April, 2004). The shapes of 2-dimensional manifolds. MAA Texas Section Meeting, Texas A&M University - Corpus Christi.
1. Faulkenberry, T. J. (March, 2003). Conway’s ZIP proof. MAA Oklahoma/Arkansas Section Meeting, University of Tulsa.
1. Faulkenberry, T. J. (March, 2002). Knot algorithms and their computational complexity. MAA Oklahoma/Arkansas Section Meeting, Henderson State University.
1. Faulkenberry, T. J. (March, 2002). Topology in the high school? National Council of Teachers of Mathematics Regional Conference, Oklahoma City, OK.
1. Faulkenberry, T. J. (March, 1999). The construction of a Riemann surface structure on a once-punctured torus. MAA Oklahoma/Arkansas Section Meeting, Arkansas Tech University.
1. Faulkenberry, T. J. (March, 1998). The classification of Markoff numbers on a once-punctured torus. MAA Oklahoma/Arkansas Section Meeting, Southern Nazarene University.

** Seminars and Invited Talks
1. Faulkenberry, T. J. (June 2020). Workshop: Bayesian statistics in numerical cognition. Invited workshop for the Math Cognition and Learning Society, Dublin, Ireland (cancelled due to COVID-19)
1. Faulkenberry, T. J. (June 2020), Workshop on Bayesian Statistics. Invited Lecture, University College - Dublin, Dublin, Ireland (cancelled due to COVID-19)
1. Faulkenberry, T. J. (April 2020). Developing an interactive web application for computing Bayes factors from summary statistics. Tarleton Psychological Sciences Day, Stephenville, TX. 
1. Faulkenberry, T. J. (April 2020) A Mathematician's Apology: What a Life in Mathematics has Taught Me about Teaching Psychology,  Keynote Address - Southwestern Teachers of Psychology Conference (SWToP), Frisco, TX (cancelled due to COVID-19)
1. Faulkenberry, T. J. (September 2019). Workshop: Bayesian statistics with JASP -- Angelo State University, San Angelo, TX.
1. Faulkenberry, T. J. (June 2019). Workshop: Bayesian statistics in numerical cognition. Math Cognition and Learning Society, Ottawa, ON.
1. Faulkenberry, T. J. (August, 2018). Workshop on R and Bayesian Statistics -- Texas Lutheran University, Seguin, TX.
1. Faulkenberry, T. J. (April, 2018). Introduction to applied Bayesian hypothesis testing -- Faculty Research Coffee Hour, Stephenville, TX.
1. Faulkenberry, T. J. (December, 2017). Mental representations of two-digit numbers. Texas A&M University - San Antonio Speakers' Series, San Antonio, TX.
1. Faulkenberry, T. J. (September, 2017). Modeling response times in mental arithmetic. Baylor University Psychology and Neuroscience Speaker Series, Waco, TX.
1. Faulkenberry, T. J. (April, 2017). The Pope, Bayes' Theorem, and Harry Potter: A statistical drama in three acts.  Tarleton Psychology Club, Stephenville, TX.
1. Faulkenberry, T. J. (March, 2017). Using mathematical modeling to understand mental arithmetic. Tarleton Math Club, Stephenville, TX.
1. Faulkenberry, T. J. (Nov. 2015). Associations between number and space in mental arithmetic.  Psychological Sciences Open House, Stephenville, TX.
1. Faulkenberry, T. J. et al. (Oct. 2015). Publishing in the digital age.  CII Panel Presentation, Stephenville, TX.
1. Faulkenberry, T. J. (June, 2015). Discussion of Marghetis et al. (2014). Carleton Math Cognition Lab, Ottawa, Ontario.
1. Smith, K. H., Riggs, B., Faulkenberry, E. D., & Faulkenberry, T. J. (May, 2014). A snapshot of preservice teacher beliefs: A factor analytic method. Tarleton State University Math Day 2014.
1. Faulkenberry, T. J. (Feb, 2014). Detecting cognitive processes via the motions of the hand: Studies in numerical cognition.  Psychology & Counseling Department Seminar, Tarleton State University.Math 
1. Faulkenberry, T. J. (April, 2013). Estimating the working memory requirements of mental arithmetic. Mathematics Education Seminar, University of Texas - Arlington, Arlington, TX.
1. Faulkenberry, T. J. (April, 2012). Reconsidering the magic number 7: Measuring and modeling working memory capacity. Mathematics Department Colloquium, Southeastern Oklahoma State University, Durant, OK.
1. Faulkenberry, T. J. (May, 2012). Arctangent approximations of $\pi$. Math Club Invited Speaker, Texas A&M University - Commerce
1. Faulkenberry, T. J. (Feb, 2012). Reconsidering the magic number 7: Measuring and modeling working memory capacity. Mathematics Department Colloquium, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2011). Introduction to LaTeX, Mathematics Department Colloquium, Texas A&M University - Commerce
1. Faulkenberry, T. J. (2009). Working memory in mathematical cognition: The case for fractions. Mathematics Department Colloquium, Texas A& M University - Commerce.
1. Faulkenberry, T. J. (2007). Uses, mis-uses, and non-uses of probability and statistics. Math club invited lecture, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2006). Continuous dynamics among phonological competitors. Cognitive Science Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2006). The evolution of color language. Cognitive Science Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2006). A computational model of event segmentation based on perceptual prediction. Cognitive Science Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2006). An introduction to latent semantic analysis. Cognitive Science Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2006). Dissections in mathematics. Math club invited lecture, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2006). Embodied cognition: The role of body and mind in abstract thought. Mathematics Education Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2005). A cognitive map for mathematical induction. Mathematics Education Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2005). Reflective abstraction in advanced mathematical thinking. Mathematics Education Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2005). Explorations in Flatland. Mathematics Colloquium, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2005). What is mathematics education research? Mathematics Education Seminar, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2004). Where do all the knots live: Templates and surface dynamics. Mathematics Colloquium, Texas A&M University - Commerce.
1. Faulkenberry, T. J. (2003). A beginner’s guide to 3-manifolds. Graduate Student Colloquium, University of North Texas.
1. Faulkenberry, T. J. (2002). Determining the shape of space. Mathematics Colloquium, University of Central Oklahoma.
1. Faulkenberry, T. J. (2002). Determining the shape of space. Mathematics Colloquium, East Central University.
1. Faulkenberry, T. J. (2002). Algorithms in topology. Mathematics Colloquium, Southeastern Oklahoma State University.

** Research Funding  

/PI unless otherwise noted.  Total funding = $263,331./

- 2019 (summer), National Science Foundation / Mathematical Association of America, National Research Experiences for Undergraduates Program (NREUP), $29,663. /CMAT: Computational Mathematics at Tarleton/
- 2018-2019, Tarleton State University, Faculty-Student Research Grant, $5000, /Modeling individual difference structures in numerical cognition/
- 2018 (spring), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $1000, /Using hierarchical Bayesian modeling to uncover the cognitive mechanisms underlying associations between number and space/
- 2017 (fall), Tarleton State University, Faculty Development Grant, $1000, /Travel: Psychonomic Society Meeting in Vancouver, BC/
- 2017 (summer), Tarleton State University, First Year Research Experience (FYRE), $4000, /Using the Wiener diffusion process to model response time distributions in a numerical decision task/  
- 2015 (fall), Tarleton State University, Faculty Development Grant, $750, /Travel: Psychonomic Society Meeting in Boston, MA/
- 2016 (summer), Tarleton State University, First Year Research Experience (FYRE), $6500, /Investigating the dynamics of operator preview effects in mental arithmetic/
- 2016 (summer), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $4000, /Testing competing models of two-digit number representation: Decomposed, holistic, or hybrid?/
- 2016 (spring), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $1000, /Testing decomposed versus holistic fraction representations via an implicit priming task/
- 2016 (spring), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $1000, /Is memory "retrieval" in single digit arithmetic really just rapid shifts of attention along a mental number line?/
- 2015 (fall), Tarleton State University, Faculty Development Grant, $750, /Travel: Psychonomic Society Meeting in Chicago, Illinois/
- 2015 (fall), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $1000, /The effects of numerical fluency on mental representations of two-digit numbers./
- 2015 (fall), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $1000, /Spatial-numerical associations in mental arithmetic./
- 2015 (summer), Tarleton State University, First Year Research Experience (FYRE), $6500, /Mental representations of two-digit numbers/
- 2015 (summer), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $3500, /Spatial-numerical associations in mental arithmetic./
- 2015 (spring), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $1000, /Are the stages of cognitive arithmetic additive or interactive? The effects of numerical surface form on an addition production task./
- 2015 (spring), Society for the Teaching of Psychology, Early Career Travel Grant, $350, /Travel: Southwestern Teachers of Psychology Conference in Wichita, Kansas/
- 2014-2015, Tarleton State University, Organized Research Grant, $9560, /Investigating the cognitive factors behind mathematics learning disability/
- 2014 (fall), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $1000, /The effects of numerical surface form on strategies for mental arithmetic verification/
- 2014 (fall), Tarleton State University, Faculty Development Grant, $508, /Travel: Psychonomic Society Meeting in Long Beach, California/
- 2014 (summer), Tarleton State University, OSRCA Undergrad. Res. Assistantship, $3500, /Using hand tracking to analyze mental representations of fractions/
- 2014 (spring), Tarleton State University, QEP Startup Grant, $1500, /Applied Learning Experience: Undergraduate Research in Mathematical Cognition/
- 2013 (fall), Tarleton State University, Faculty Development Grant, $630, /Travel: Psychonomic Society Meeting in Toronto, Ontario/
- 2012-2013, National Science Foundation: Robert Noyce Scholarship Program, $174,020 (Co-PI with Ben Jang), /Building the Capacity for Math and Science Teacher Training/
- 2010, Texas A&M University – Commerce, OSP Research Grant, $5000, /Mouse Tracking in Mathematical Cognition/
- 2008, Texas A&M University – Commerce, OSP Mini Grant, $600, /IoLab Button Box for Psyscope X/
  
** Editorial roles
- Associate Editor (2019-present): /Journal of Numerical Cognition/
- Associate Editor (2017-present): /Journal of European Psychology Students/
- Associate Editor (2016-present): /Journal of Psychological Inquiry/
- Guest Editor (2016-2018): /Journal of Numerical Cognition/
- Associate Editor (2017-2019): /Frontiers in Psychology: Cognition Section/
- Review Editor (2016-2017): /Frontiers in Psychology: Cognition Section/
** Reviewing
   
- Ad hoc reviewer for the following journals: /Acta Psychologica, Attention, Perception, & Psychophysics, Behavior Research Methods, British Journal of Developmental Psychology, Canadian Journal of Experimental Psychology, Cognitive Processing, Cognition, Cognitive Science, Frontiers in Psychology, Journal of Cognitive Psychology, Journal of Experimental Child Psychology, Journal of Numerical Cognition, Learning and Individual Differences, Mathematics Teacher, Mathematics Teaching in the Middle School, Meta-Psychology, Proceedings of the Research Council on Mathematics Learning, Psychological Methods, Psychonomic Bulletin and Review, Quarterly Journal of Experimental Psychology/
- External Examiner
  - 2017, Corinna Jones, Ph.D., University of Huddersfield, UK
- Panelist/Reader
  - 2017-2019, Judge, American Statistical Association Statistics Project Competition
  - 2015-2020, Reader, AP Statistics Exam, Kansas City, MO
  - 2012-2015, Panelist, National Science Foundation, Washington, DC
 
- Textbook reviewer for Psychology Press, Routledge, Sage, Taylor & Francis, Cambridge Univ. Press
    
** Professional Memberships 
- American Mathematical Society
- American Statistical Association
- Mathematical Association of America
- Mathematical Cognition and Learning Society
- Psychonomic Society
- Society for Mathematical Psychology
- Southwestern Psychological Association (SWPA)

** Professional Service

National/regional service 

- Secretary/Treasurer, MAA Special Interest Group (SIGMAA) on Statistics Education (elected 2020-2022)
- ASA-MAA Joint Committee on Statistics Education (appointed 2020-2023)
- Treasurer, Southwestern Psychological Association (appointed, 2017-2023)	
- Program Review Committee member, Psychonomic Society (appointed 2018-2021)
- Texas Representative, Southwestern Psychological Association (elected, 2015-2017)
- Steering Committee Member, Southwestern Teachers of Psychology (appointed, 2015-2016)
- Nominating Committee Chair, Southwestern Psychological Association (appointed, 2015)
- Advisory Board Member, Collaborative Replications and Education Project (CREP) (appointed, 2014-2016)
- Session Chair, Psychonomics Annual Meeting (2014, 2015)
- Session Chair, Southwestern Psychological Association Meeting (2015)
- Conference Committee Member, Research Council on Mathematics Learning (elected, 2012-2015)
	
University service

- Chair, Institutional Review Board (IRB) (2018-present)
- Member, General Education and Academic Assessment Committee (2019-present)
- Faculty Research Fellow (2018-2019)
- Official Advisor for Alpha Chi Honor Society, Tarleton (2015-present)
- State Non-Funded Course Review Group, Member, Tarleton (2015-present)
- University Research Committee, Member, Tarleton (2015-present)
- Student Research and Creative Activity Advisory Committee, Member, Tarleton (2013-present)
- Member, Institutional Review Board (IRB) (2017-2018)
- Faculty Fellow, Tarleton (2016-2018)
- Honors Advisory Committee for College of Education, Member, Tarleton (2015-2017)
- Session Chair and Judge, TAMUS Pathways Symposium (2017)
- University ALE Task Force, Member, Tarleton (2016-2017)
- Curriculum Committee, College of Education, Member, Tarleton (2014-2017)
- Greater Expectations Task Force, Member, Tarleton (2014-2015)
- Student Marshall, College of Education Commencement, Tarleton (Sp14, Sp15, Fa15)
- Session Chair and Judge, Tarleton Research Symposium (2014, 2015)
- External Search Committee member, Department of Engineering, TAMU-C (2012-2013)
- University Honors Council, Member, TAMU-C (2012-2013)
- Liberal Studies Committee, Member, TAMU-C (2012-2013)
- Developmental Appeals Committee, Member, TAMU-C (2010-2012)		

Department service

- Human subjects research pool coordinator, Tarleton (2018-present)
- Organized /Psychological Sciences Day/, Tarleton (2017-present)
- Search Committee Chair, Department of Psychological Sciences, Tarleton (2014, 2015, 2020)
- Texan Orientation, Department of Psychological Sciences, Tarleton (2014-2018)
- Texan Tour Speaker, Department of Psychological Sciences, Tarleton (2015)
- Organizer, Psychology Department Seminar, Tarleton (2013-2014)
- Psychology Scholarship Committee, Tarleton (2013-2015)
- Psychology Undergraduate Programs Committee, Member, TAMU-C (2011-2012)
  
** Courses Taught

Tarleton State University

- PSYC 2301: General Psychology (Honors), Fall 13,14,15
- PSYC 2317: Statistical Methods for Psychology, Fall 19, Sp 20
- PSYC 2301: General Psychology, Summer 14,15
- PSYC 3301: Psychology of Learning, Fall 13,14,15,16
- PSYC 3303: Educational Psychology, Fall 13; Spring 14; Summer 14,15,16
- PSYC 3309: Writing in Psychology, Spring 16
- PSYC 3320: Psycholinguistics, Summer 17,18,19,20
- PSYC 3330: Elem Statistics for Behav Science, Fall 14,15,16,17,18; Sp 15,16,17,18; Su 16,17,18
- PSYC 3435: Prin Research for Behav Science, Fall 14,15,16,17,18,19; Sp 15,16,17,18,19; Su 15,16,17
- PSYC 4301: Psychological Tests and Measurements, Sp 20
- PSYC 4386: Advanced Statistical Methods, Spring 14
- PSYC 4386: Methods in Experimental Psychology, Spring 15; Fall 15
- PSYC 4386: Problems in Numerical Cognition, Fall 15
- PSYC 5303: Theories of Learning, Fall 16
- HONS 3385: Honors Seminar (Numerical Cognition), Spring 15
- PSYC 5301: Research Methods, Spring 14,15,17,18,19
- PSYC 5304: Human Development, Spring 14
- PSYC 5316: Advanced Quantitative Methods, Fall 17,18,19
- PSYC 5322: Psychometrics, Sp 20
- PSYC 5379: Advanced Psycholinguistics, Summer 17,18,19,20
- EDAD 6313: Statistical Methods for Educational Leadership, Spring 16

** Student Mentoring
*** Masters Thesis Chair
- Kristen Bowman (Applied Psychology, Tarleton, graduated 2020)
- Chelsea Bradley (Applied Psychology, Tarleton, graduated 2018)

*** Doctoral Committees

- Jeni McNeely (Educational Leadership, Tarleton, graduated 2016)
- Trina Geye (Psychology, TAMU-C, graduated 2016)
- Stephen McDaniel (Psychology, TAMU-C, in progress)
- Beth Nikopoulous (Psychology, TAMU-C, graduated 2015)
- Donna Peters (Psychology, TAMU-C, graduated 2013)
	
*** Masters Committees

- Kayli Colpitts (Applied Psychology, Tarleton, in progress)
- Kody Lamb (Applied Psychology, Tarleton, graduated 2018)
- Trina Geye (Psychology, TAMU-C, graduated 2015)
- Beth Nikopoulous (Psychology, TAMU-C, graduated 2013)
- Heather Oetker (Special Education, TAMU-C, graduated 2012)
- Joshua Patterson (Mathematics, TAMU-C, graduated 2011)

*** Honors Thesis Chair

- Kristen Bowman (Psychology, Tarleton, graduated 2018), /Nonwords induce reverse priming effects in a lexical decision task/
- Anissa Eid (Psychology, Tarleton, graduated 2018), /Cognitive mechanisms underlying spatial-numerical associations/
- Paige Woodard (Psychology, Tarleton, graduated 2017), /Mental arithmetic: Relationship between encoding and calculation processes/
- Sarah Montgomery (High Honors in Psychology, TAMU-C, graduated 2013), /Measuring the Working Memory Requirements of Mental Arithmetic/
- Emily Dalton (Honors in Psychology, TAMU-C, graduated 2013), /The Effects of Generation on False Memory for Numbers/
- Kaytlin Reid (Honors in Interdisciplinary Studies, TAMU-C, graduated 2013), /The Role of Working Memory in Mental Fraction Computation/
- Douglas Boney (Honors in Mathematics, TAMU-C, graduated 2013), /Knot Polynomials/
- Samantha Reece (Honors in Sociology, TAMU-C, graduated 2012), /The Effects of Stereotype Threat on Cheating Behavior in Mathematics/

*** Honors Thesis Committees

- Carmen Phelps (English, TAMU-C, 2013)
- Morgan Lutz (Psychology, TAMU-C, 2013)
- Nick Bredberg (Physics, TAMU-C, 2012)
- Kallie Hinton (Mathematics Education, TAMU-C, 2011)
- Lindsey Preston (Mathematics Education, TAMU-C, 2011)

  
