---
title: "Syllabus"
output: pdf_document
---

## PSYC 2301 -- General Psychology

- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: TBA
- Email: faulkenberry@tarleton.edu
- Twitter: [tomfaulkenberry](http://twitter.com/tomfaulkenberry)
- Web: [tomfaulkenberry.github.io](http://tomfaulkenberry.github.io)
- Phone: 254-968-9816

## Course description

An overview of psychology, the scientific study of human behavior and mental (cognitive) processes and the factors that influence these processes.

This course is a survey of the scientific study of human nature, including how the mind works, and how the brain supports the mind. Topics will include the mental and neural bases of perception, emotion, learning, memory, cognition, child development, personality, psychopathology, and social interaction. Students will consider how such knowledge relates to debates about nature and nurture, free will, consciousness, human differences, self, and society.

I approach psychology as a practicing scientist. To me, psychological science provides models that help to understand and predict human behavior. This perspective is one of the primary guiding forces behind how I approach my lectures, class discussions, and out-of-class assignments.

## Course materials

We will be reading selected chapters from Stangor’s Introduction to Psychology, a free textbook. Materials will be available on Blackboard. In addition, you might find an inexpensive general psychology textbook helpful (make sure it is no more than 5 years old).

## Student learning outcomes

1. Describe the scientific background of psychological science and how this perspective has changed over the years.
1. Describe the factors influencing each of the course topics listed above.
1. Learn how to ask (and design studies to answer) empirical questions in psychological science.
1. Write about psychological science.


## Requirements and grading

- Exam 1 (60 pts)
- Exam 2 (100 pts)
- Exam 3 (150 pts)
- Unit quizzes (90 pts)
- Writing assignments (100 pts)
- *Total = 500 points*

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

### Exams (62% of grade)

There will be three total exams throughout the semester, covering material from specified course units. Exam questions will be primarily multiple choice with occasional short answer questions.  

Dates:

- Exam 1 (Wednesday, June 15)
- Exam 2 (Friday, June 24)
- Exam 3 (Wednesday, July 6)

### Unit quizzes (18% of grade)

At the conclusion of every unit, you will complete a short multiple choice quiz over the unit’s content. There will be 9 such quizzes, each worth 10 points (or 2%) toward your total grade.

### Writing assignments (20% of grade)

There will be two writing assignments for the course, worth 50 points each (a total of 100 points). They are designed to get you thinking in depth about topics as we go along and to give you some writing experience. Each writing assignment will be a minimum of 1000 words in length, typed (double- spaced), in a normal 12 point font (Times New Roman or Arial only, please). More detailed information (including due dates) is available on Blackboard.

## Course Communication

I am your primary resource for this course. I AM an experimental psychologist, so I do the stuff I teach about daily. Hence, my primary interest is for you to learn this material and do well in the course. You may contact me using any means necessary (email and Twitter are the best). That being said, many people prefer to use Blackboard messages. I don’t mind these, but keep in mind that I may not receive your message until I actually open Blackboard. With email/Twitter, if you send me a message at 9:00 pm, I may actually respond pretty quickly. 

## University Policy on "F" Grades

Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

## Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.


## Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act (ADA) and other federal, state, and local laws relative to the provision of disability services. Students with disabilities attending Tarleton State University may contact the Office of Disability Services at (254) 968-9478 to request appropriate accommodation. Furthermore, formal accommodation requests cannot be made until the student has been officially admitted to Tarleton State University.


**Note:  any changes to this syllabus will be communicated to you by the instructor!**

## Semester schedule

Unit | Topics   | Due date
---- | -------- | --------
1 | Psychology as a science | Friday, June 10
2 | The brain: Structure and function | Monday, June 13
. | **Exam 1** | **Wednesday, June 15**
3 | Sensation and perception | Friday, June 17
4 | Learning | Monday, June 20
5 | Memory | Wednesday, June 22
. | **Exam 2** | **Friday, June 24**
6 | Language | Monday, June 27
7 | Intelligence | Wednesday, June 29
8 | Personality | Friday, July 1
9 | Emotion and motivation | Monday, July 4
. | **Exam 3** | **Wednesday, July 6**

Note: all quizzes and exams must be completed by 11:59 pm on their due date.