---
title: "Syllabus"
output: pdf_document
---

## PSYC 3330 - Elementary Statistics for the Behavioral Sciences

- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 9-11, TR 1-3
- Email: faulkenberry@tarleton.edu
- Twitter: [tomfaulkenberry](http://twitter.com/tomfaulkenberry)
- Website: http://tomfaulkenberry.github.io
- Phone: 254-968-9816

## Course description

Statistical methods are the primary tool for research in psychology.  They are what allow us as researchers to make consistent, data-driven decisions.  As such, this is an extremely important course and one that I take very seriously as your professor.

The topics we will cover this semester will include descriptive statistics (how we describe data) and inferential statistics (how we make decisions about data).  Specifically, this includes central tendency, variability, correlation, the distinction between populations and samples, hypothesis testing, statistical significance, and a variety of inferential tests that we can apply to data, including t-tests and analysis of variance.

## Course materials

- *Statistics for the Behavioral Sciences (10th ed.)* by Gravetter and Wallnau [(Amazon link)](http://www.amazon.com/Statistics-Behavioral-Sciences-MindTap-Psychology/dp/1305504917/)
- Note:  older editions of this textbook are fine.  Feel free to find a used copy of an older edition on Amazon.


## Student learning outcomes

1. Identify variables under study (including independent and dependent variables)
2. Choose appropriate measures of descriptive statistics
3. Select and perform appropriate inferential statistics
4. Draw appropriate statistical conclusions from results of analyses

## Requirements and grading

- Exam 1 (60 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (100 pts)
- Weekly quizzes (100 pts)
- Homework exercises (100 pts)
- Research requirement (40 pts)
- *Total = 600 points*

Grades will be assigned based on the percentage of points you accumulate out of these 600 points.  I will use the standard grading scale of A=90%, B=80%, etc.

### Exams (60% of grade)

There will be four total exams throughout the semester, occurring approximately once every three to four weeks.  They will cover material from lectures and quizzes.  Exam questions will be a mix of multiple choice and short answer.  

Exam dates:

- Exam 1 (Thursday, Sep 22)
- Exam 2 (Thursday, Oct 20)
- Exam 3 (Thursday, Dec 1)
- Final exam (Saturday, Dec 10, 8-10:30 am)

### Unit quizzes (17% of grade)

At the end of each unit, you will complete a quiz over the content of that unit. Each quiz counts for 10 possible points.  Since there are 10 units, you will earn up to 100 points for your quiz grade.  Note that for each week, a quiz will be administered online via Blackboard and will be due Sunday night at 11:59 pm.

### Homework exercises (17% of grade)

In order to practice the statistical concepts you learn this semester, you will complete short homework assignments for every unit.  A set of homework exercises (no more than 10 exercises per unit) will be provided to you on Blackboard.  You may work collaboratively on the homework exercises, but any work submitted must reflect your own understanding of the material (in other words, don't just copy someone else's work to submit).  Completed exercises should be handwritten (with all work shown) and scanned to submit on Blackboard.  Note that if you do not have access to a good scanner, you may instead just take photos of the completed pages with your phone and upload these photos.  Just make sure to save *small* or *medium* versions of the photos before submitting.  Homeworks for a given unit will need to be submitted by Sunday at 11:59 pm.

### Research requirement (6% of grade)

Research is the lifeblood of psychology!  In order to promote your growth as a psychological scientist, you will be required to participate in 2 "units"" of research over the course of the semester.  Roughly defined, a "unit"" of research consists of either (1) participation in one hour of psychological experiments, usually offered right here in the Psychology department at Tarleton, or (2) a 3-5 page critical reflection of an empirical research article related to human learning and/or cognition, usually chosen by me.  Instructions for participation will be given in class.


## Course Communication

I am your primary resource for this course. I AM an experimental psychologist, so I do the stuff I teach about daily. Hence, my primary interest is for you to learn this material and do well in the course. You may contact me using any means necessary (email and Twitter are the best). That being said, many people prefer to use Blackboard messages. I don’t mind these, but keep in mind that I may not receive your message until I actually open Blackboard. With email/Twitter, if you send me a message at 9:00 pm, I may actually respond pretty quickly. 

## University Policy on "F" Grades

Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

## Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam/quiz taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

## Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act and other applicable laws. If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.

**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
## Semester Schedule

Unit | Dates         | Topic
---- | ------------- | -------------------------------------------------
1 | Aug 29-Sep 2 | Displaying data
2 | Sep 5-9 | Descriptives 1: central tendency, variation, and z-scores
3 | Sep 12-16 | Descriptives 2: correlation
. | Sep 19-23 | **Exam 1**
4 | Sep 26-30 | The normal distribution: measuring likelihood
5 | Oct 3-7 | The logic of hypothesis testing
6 | Oct 10-14 | Testing means of samples of *known* populations ($z$-tests)
. | Oct 17-21 | **Exam 2**
7 | Oct 24-28 | Testing means of samples of *unknown* populations ($t$-tests)
8 | Oct 31-Nov 4 | More $t$-tests (independent samples, etc.)
9 | Nov 7-11 | Analysis of variance (ANOVA): one independent variable
10 | Nov 14-18 | Analysis of variance (ANOVA): two independent variables
. | Nov 21-25 | *No coursework during week of Thanksgiving holiday*
. | Nov 28-Dec 2 | **Exam 3** 
. | Dec 5-9 | Course review (no class on Thursday)
. | Dec 12-16 | **Final exam on Saturday, Dec 10, 8-10:30 am**

