---
title: "Syllabus"
output: pdf_document
---

## PSYC 5303 - Theories of Learning

- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 9-11, TR 1-3
- Email: faulkenberry@tarleton.edu
- Twitter: [tomfaulkenberry](http://twitter.com/tomfaulkenberry)
- Website: http://tomfaulkenberry.github.io
- Phone: 254-968-9816

## Course description

In this introductory level graduate course, we will survey a wide range of persepectives (both historical and current) on the theoretical principles of learning and memory.  To accomplish this, you will read a variety of book chapters and journal articles that are chosen to help you develop a deep knowledge base of the theories, empirical methods, and applications of human learning and memory.  As this course is foundational to your future study in the MS in Applied Psychology, a portion of the course will be devoted to helping you develop a quantitative research proposal in which you will design an experiment involving some topic from our course in either a theoretical or applied context.

## Course materials

There are several relevant textbooks for this course, but some are hard to find and/or expensive.  Hence, I will be providing copies of selected chapters as we need them.  However, you are welcome to find your own copies of these books, as they are very good.

- Bower, G. H., & Hilgard, E. R. (1981). *Theories of Learning* (5th ed.). Englewood Cliffs, NJ: Prentice-Hall, Inc.
- Eichenbaum, H. (2008). *Learning & Memory*. New York: W. W. Norton Company.
- Neath, I., & Surprenant, A. M. (2003). *Human memory* (2nd ed.). Belmont, CA: Wadsworth.

## Student learning outcomes

1.  Discuss the experimental procedures used to study human learning and memory.
1.	Demonstrate an understanding of both contemporary and historically important conceptual frameworks in the study of human learning and memory.
1.	Discuss the theoretical arguments that have motivated research on human learning and memory.
1.  Develop, write, and present a proposal to experimentally investigate some theoretical or applied aspect of human learning and memory.

## Requirements and grading

Regular attendance and full participation in each weekly class session are essential requirements. You must carefully, thoroughly, and thoughtfully complete all reading and writing assignments *prior* to each class.  

Each week, you will turn in a one-page article summary about *one* of the assigned student readings (see schedule).  Your summary must contain the following:

- describe the motivation for the experiment (i.e., what problem was the paper attempting to solve?)
- a brief description of the method, particularly describing the key dependent variables (what was measured) and independent variables (what was manipulated)
- a conceptual description of the results (don't list the statistical results, just tell me the "big picture")

In addition, two students will serve as discussion leaders each week.  This means they will have carefully read their assigned paper, read additional material, and prepared an oral presentation (with appropriate slides and/or handouts).  Class presentations should be short and to the point (no more than fifteen minutes for the assigned paper and an additional ten-fifteen minutes for discussion, giving a total of 30 minutes for each presenter).

In addition to the weekly contributions during class, there will be two in-class exams (one during our Week 8 meeting and one during our Week 14 meeting).  The week prior to each exam you will be given a set of 10-15 potential essay questions.  Each student is expected to work INDEPENDENTLY when preparing for the exam.  Answers should include sufficient empirical evidence (not just anecdotes), giving descriptions of specific experiments that lead to your conclusions.  Five questions will be selected for the exam, and you will be asked to answer 4 out of the 5 essay questions. The questions will be based on material covered in lecture, assigned readings, and class discussions.  The exams will be given in class, and you will not be able to consult any external materials.  In other words, you will have to retrieve from your memory your responses to the practice exam.  Violations will result in a grade of ZERO on the exam.

Finally, you will be asked to put together an empirical proposal to investigate some theoretical or applied issue in human learning and memory.  The ideal proposal will be one which you could potentially implement as your thesis or applied project.  We will develop these proposals in three components.  First, on Week 7 you will turn in a brief paragraph that gives a conceptual description of your proposal idea.  This paragraph will not be graded, but will provide the basis of feedback from me that will help you to refine your idea.  The paragraph must describe the questions your research proposal will address and the methodology you intend to use, and provide at least two relevant "key" references.

Next, on Week 10 you will turn in an outline of your proposal and give a short in-class presentation of your proposal.  Based on the feedback that I (and your colleagues) give you on this draft, you will write a final manuscript for your proposal (with full Abstract, Introduction, Methods, Hypothesized Results and Discussion) and give an oral presentation of your experimental paper on Week 15.  Following both the Week 10 and Week 15 presentations, written peer reviews will be required from each member of the class.  Details on the requirements for this project will be distributed in a few weeks.

These various components of your class performance will contribute to your grade as follows:

- Midterm exam (25%)
- Final exam (25%)
- Weekly article summaries (10%)
- Leading discussions of assigned readings (10%)
- Research proposal (30%), consisting of:
    - Initial written and oral proposal (5%)
    - Final presentation of proposal (10%)
    - Final manuscript of proposal (10%)
    - Peer reviews of colleagues' initial and final presentations (5%)

## Course Communication

I am your primary resource for this course. I AM an experimental psychologist, so I do the stuff I teach about daily. Hence, my primary interest is for you to learn this material and do well in the course. You may contact me using any means necessary (email and Twitter are the best). That being said, many people prefer to use Blackboard messages. I don’t mind these, but keep in mind that I may not receive your message until I actually open Blackboard. With email/Twitter, if you send me a message at 9:00 pm, I may actually respond pretty quickly. 

## University Policy on "F" Grades

Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

## Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam/quiz taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

## Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act and other applicable laws. If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.

**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
## Semester Schedule

- **Week 1** (8/31): Introduction and syllabus overview; what is learning?
    - Background reading:
        - Chapter 1 of Eichenbaum
    - Student presentations:
        - *none this week*

- **Week 2** (9/7): Mechanisms of classical conditioning
    - Background reading:
        - Chapter 5 of Eichenbaum
    - Student presentations:
        - Clark, R. E., & Squire, L. R. (1998). Classical conditioning and brain systems: The role of awareness. *Science, 280*(3), 77-81.
        - Orr, S. P., et al. (2000). De novo conditioning in trauma-exposed individuals with and without posttraumatic stress disorder. *Journal of Abnormal Psychology, 109*(2), 290-298
        
- **Week 3** (9/14): Mechanisms of instrumental conditioning
    - Background reading:
        - Chapter 6 of Eichenbaum
    - Student presentations:
        - Skinner, B. F. (1948). Superstition in the pigeon. *Journal of Experimental Psychology, 38*, 168-172.
        - Powell, R. W. (1972). Operant conditioning in the common crow (Corvus brachyrhynchos). *The Auk, 89*(4), 738-742.

- **Week 4** (9/21): Human associative learning
    - Background reading:
        - Chapter 6 of Bower & Hilgard
    - Student presentations:
        - Roediger, H. L., & Karpicke, J. D. (2006). Test-enhanced learning: Taking memory tests improves long-term retention. *Psychological Science, 17*(3), 249-255.
        - Roediger, H. L., & Crowder, R. G. (1976). A serial position effect in recall of United States presidents. *Bulletin of the Psychonomic Society, 8*(4), 275-278.

- **Week 5** (9/28): The classic multi-store model of human memory
    - Background reading:
        - Chapter 3 of Neath and Surprenant
    - Student presentations:
        - Glanzer, M., & Cunitz, A. R. (1966). Two storage mechanisms in free recall. *Journal of Verbal Learning and Verbal Behavior, 5*, 351-360.
        - Bjork, R. A., & Whitten, W. B. (1974). Recency-sensitive retrieval processes in long-term free recall. *Cognitive Psychology, 6*, 173-189.

- **Week 6** (10/5): Working memory
    - Background reading:
        - Chapter 4 of Neath and Surprenant
    - Student presentations:
        - Trbovich, P. L., & LeFevre, J. (2003). Phonological and visual working memory in mental addition. *Memory & Cognition, 31*(5), 738-745.
        - Miyake, A., & Friedman, N. P. (2012). The nature and organization of individual differences in executive functions: Four general conclusions. *Current Directions in Psychological Science, 21*(1), 8-14.

- **Week 7** (10/12): Encoding and retrieval processes / *turn in paragraph describing your experimental proposal*
    - Background reading:
        - Chapter 5 of Neath and Surprenant
    - Student presentations:
        - Bjork, R. A., & Allen, T. W. (1970). The spacing effect: Consolidation or differential encoding? *Journal of Verbal Learning and Verbal Behavior, 9*, 567-572.
        - Mulligan, N. W., & Lozito, J. P. (2006). An asymmetry between memory encoding and retrieval: Revelation, generation, and transfer-appropriate processing. *Psychological Science, 17*(1), 7-11.
        
- **Week 8** (10/19): *Midterm exam*, after which we will discuss your research proposals

- **Week 9** (10/26): Forgetting
    - Background reading:
        - Chapter 6 of Neath and Surprenant
    - Student presentations:
        - Anderson, M. C., Bjork, E. L., & Bjork, R. A. (2000). Retrieval-induced forgetting: Evidence for a recall-specific mechanism. *Psychonomic Bulletin & Review, 7*(3), 522-530.
        - Campbell, J. I. D., & Thompson, V. A. (2012). Retrieval-induced forgetting of arithmetic facts. *Journal of Experimental Psychology: Learning, Memory, and Cognition, 38*(1), 118-129.

- **Week 10** (11/2): Implicit memory / *Outline of research proposals due, in-class presentations of outlines*
    - Background reading:
        - Chapter 7 of Neath and Surprenant
    - Student presentations:
        - *coming soon*


- **Week 11** (11/9): Knowledge representations in long-term memory
    - Background reading:
        - Chapter 10 of Neath and Surprenant
    - Student presentations:
        - *coming soon*

- **Week 12** (11/16): Mental imagery
    - Background reading:
        - Chapter 11 of Neath and Surprenant
    - Student presentations:
        - *coming soon*

- **Week 13** (11/23): *no class due to Thanksgiving holiday*

- **Week 14** (11/30): *Final exam*
        
- **Week 15** (12/7): In-class presentations





