---
title: "Syllabus"
output: pdf_document
---

## PSYC 3301 - Psychology of Learning

- Professor: Thomas J. Faulkenberry, Ph.D
- Office: Math 319
- Office hours: MWF 9-11, TR 1-3
- Email: faulkenberry@tarleton.edu
- Twitter: [tomfaulkenberry](http://twitter.com/tomfaulkenberry)
- Website: http://tomfaulkenberry.github.io
- Phone: 254-968-9816

## Course description

This course expands upon the two major theoretical perspectives in the study of learning: the behavioral approach, and the cognitive approach. In this course we will look at similarities and differences between these two approaches to a variety of topics, beginning with classical and operant conditioning, proceeding to verbal learning and concept learning, and ending with coverage of memory and forgetting. A theme that will be developed is that the two approaches are better seen as complementary rather than as competitive, and that one gets a more comprehensive picture of the learning process by considering both approaches as opposed to one alone. This course also has a methodological emphasis. From the text, lectures, and various in-class activities and demonstrations, students will see how abstract issues are translated into specific experimental procedures, how general conclusions are drawn from specific findings, and how these conclusions are critically evaluated and related to the original issues. 

## Course materials

- *Learning & Memory: Basic Principles, Processes, and Procedures* by W. S. Terry (4th ed.) [(Amazon link)](https://www.amazon.com/Learning-Memory-Principles-Processes-Procedures/dp/0205658628)


## Student learning outcomes

1.  Discuss the experimental procedures used to study classical and operant conditioning.
2.	Describe major controversies that have motivated research in classical/operant conditioning.
3.	Discuss the experimental procedures used to study verbal learning.
4.	Demonstrate an understanding of both contemporary and historically important conceptual frameworks in the study of memory and forgetting.
5.	Discuss major controversies that have motivated research on both semantic and episodic memory.


## Requirements and grading

- Exam 1 (60 pts)
- Exam 2 (100 pts)
- Exam 3 (100 pts)
- Final exam (100 pts)
- Weekly quizzes (100 pts)
- Research requirement (40 pts)
- *Total = 500 points*

Grades will be assigned based on the percentage of points you accumulate out of these 500 points.  I will use the standard grading scale of A=90%, B=80%, etc.

### Exams (72% of grade)

There will be four total exams throughout the semester, occurring approximately once every three to four weeks.  They will cover material from lectures and quizzes.  Exam questions will be a mix of multiple choice and short answer.  

Exam dates:

- Exam 1 (Friday, Sep 30)
- Exam 2 (Friday, Oct 28)
- Exam 3 (Friday, Dec 2)
- Final exam (Wednesday, Dec 14, 8-10:30 am)

### Weekly quizzes (20% of grade)

Every week that doesn't have a regular exam, you will complete a quiz over the week's content. Each quiz counts for 10 possible points, and your best 10 scores will contribute to your overall quiz grade (max 100 points).  

### Research requirement (8% of grade)

Research is the lifeblood of psychology!  In order to promote your growth as a psychological scientist, you will be required to participate in 2 "units"" of research over the course of the semester.  Roughly defined, a "unit"" of research consists of either (1) participation in one hour of psychological experiments, usually offered right here in the Psychology department at Tarleton, or (2) a 3-5 page critical reflection of an empirical research article related to human learning and/or cognition, usually chosen by me.  Instructions for participation will be given in class.


## Course Communication

I am your primary resource for this course. I AM an experimental psychologist, so I do the stuff I teach about daily. Hence, my primary interest is for you to learn this material and do well in the course. You may contact me using any means necessary (email and Twitter are the best). That being said, many people prefer to use Blackboard messages. I don’t mind these, but keep in mind that I may not receive your message until I actually open Blackboard. With email/Twitter, if you send me a message at 9:00 pm, I may actually respond pretty quickly. 

## University Policy on "F" Grades

Beginning in Fall 2015, Tarleton will begin differentiating between a failed grade in a class because a student never attended (F0 grade), stopped attending at some point in the semester (FX grade), or because the student did not pass the course (F) but attended the entire semester. These grades will be noted on the official transcript. Stopping or never attending class can result in the student having to return aid monies received.  For more information see the Tarleton Financial Aid website.

## Academic Honesty

Cheating, plagiarism (submitting another person’s materials or ideas as one’s own), or doing work for another person who will receive academic credit are all disallowed. This includes the use of unauthorized books, notebooks, or other sources in order to secure of give help during an examination, the unauthorized copying of examinations, assignments, reports, or term papers, or the presentation of unacknowledged material as if it were the student’s own work. Disciplinary action may be taken beyond the academic discipline administered by the faculty member who teaches the course in which the cheating took place.

In particular, any exam/quiz taken online must be completed without the aid of any unauthorized resource (including using any search engine, Google, etc.).  Authorized resources are limited only to the official textbook and any lecture notes from the course.  Any other authorized resources will be provided to you before the exam.  The minimum sanction for violation of this policy is a grade of 0 on the affected exam.

## Students with Disabilities Policy

It is the policy of Tarleton State University to comply with the Americans with Disabilities Act and other applicable laws. If you are a student with a disability seeking accommodations for this course, please contact the Center for Access and Academic Testing, at 254.968.9400 or caat@tarleton.edu. The office is located in Math 201. More information can be found at www.tarleton.edu/caat or in the University Catalog.

**Note:  any changes to this syllabus will be communicated to you by the instructor!**
 
## Semester Schedule

Week | Dates         | Topic
---- | ------------- | -------------------------------------------------
1 | Aug 29-Sep 2 | Course introduction: What is learning?
2 | Sep 5-9 | Classical conditioning: Basic methods and phenomena
3 | Sep 12-16 | Classical conditioning: Theoretical perspectives
4 | Sep 19-23 | Operant conditioning
5 | Sep 26-30 | **Review and Exam 1**
6 | Oct 3-7 | Verbal learning
7 | Oct 10-14 | Conceptual approaches to human memory
8 | Oct 17-21 | Short-term memory
9 | Oct 24-28 | **Review and Exam 2**
10 | Oct 31-Nov 4 | Encoding processes
11| Nov 7-11 | Storage and retrieval processes
12 | Nov 14-18 | Implicit memory processes
13| Nov 21-25 | *No coursework during week of Thanksgiving holiday*
14| Nov 28-Dec 2 | **Review and Exam 3** 
15| Dec 5-9 | Recap: a modern look at learning/memory
16| Dec 12-16 | **Final exam on Wednesday, Dec 14, 8-10:30 am**

