#+TITLE: 
#+AUTHOR:
#+OPTIONS: toc:nil num:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../bjm.css" />

* Learning Statistics with JASP

Welcome to the homepage for the book /Learning Statistics with JASP: A Tutorial for Psychology Students and Other Beginners/, written by [[https://compcogscisydney.org/][Danielle J. Navarro]], [[https://www.brookes.ac.uk/templates/pages/staff.aspx?uid=p0072582][David R. Foxcroft]], and [[https://tomfaulkenberry.github.io][Thomas J. Faulkenberry]].

/Learning Statistics with JASP/ is a free textbook covering the basics of statistical inference for beginners in psychology and related applied disciplines. It uses the free software package [[http://jasp-stats.org][JASP]]. Written in a lively, conversational style, it provides the reader with a perfect balance of readability and rigor, and gives students a modern view of statistical inference in the psychological and behavioral sciences. 

** Download the book

/Learning Statistics with JASP/ is available as a free PDF download. You can download the entire book in one file (~7MB), or you can download specific chapters below:

- Complete book ([[file:lsj.pdf][pdf]])
- Table of contents ([[file:chapters/toc.pdf][pdf)]]
- Chapter 1: Why do we learn statistics? ([[file:chapters/chapter1.pdf][pdf]])
- Chapter 2: A brief introduction to research design ([[file:chapters/chapter2.pdf][pdf]])
- Chapter 3: Getting started with JASP ([[file:chapters/chapter3.pdf][pdf]])
- Chapter 4: Descriptive statistics ([[file:chapters/chapter4.pdf][pdf]])
- Chapter 5: Drawing graphs ([[file:chapters/chapter5.pdf][pdf]])
- Chapter 6: Introduction to probability ([[file:chapters/chapter6.pdf][pdf]])
- Chapter 7: Estimating unknown quantities from a sample ([[file:chapters/chapter7.pdf][pdf]])
- Chapter 8: Hypothesis testing ([[file:chapters/chapter8.pdf][pdf]])
- Chapter 9: Categorical data analysis ([[file:chapters/chapter9.pdf][pdf]])
- Chapter 10: Comparing two means ([[file:chapters/chapter10.pdf][pdf]])
- Chapter 11: Correlation and linear regression ([[file:chapters/chapter11.pdf][pdf]])
- Chapter 12: Comparing several means (one-way ANOVA) ([[file:chapters/chapter12.pdf][pdf]])
- Chapter 13: Factorial ANOVA ([[file:chapters/chapter13.pdf][pdf]])
- Chapter 14: Bayesian statistics ([[file:chapters/chapter14.pdf][pdf]])
- Epilogue ([[file:chapters/epilogue.pdf][pdf]])

** Data sets for book

The example datasets that are used in /Learning Statistics with JASP/ are available for download in two ways.

- you can download one [[file:data.zip][ZIP file]] containing all data files and save it to your computer (recommended)
- you can download specific datasets from the book's GitHub [[https://github.com/tomfaulkenberry/JASPbook/tree/master/data][repository]] 

** Source code

This book was written entirely in LaTeX, and all source code for the book can be found on [[http://github.com/tomfaulkenberry/JASPbook][GitHub]].

** Contributing?

This book is completely open source, which means you are free to adapt it in any way you wish (as long as appropriate credit is given to the authors..see below). However, if you find issues that you would like to see in this posted version, feel free to contact [[mailto:faulkenberry@tarleton.edu?subject=JASP book issue][me]] by email.  Even better would be to log an issue on [[https://github.com/tomfaulkenberry/JASPbook/issues][GitHub]].

#+HTML: <br>

This book is an adaptation of Navarro, D.J., & Foxcroft, D. R. (2019). [[http://learnstatswithjamovi.com][learning statistics with jamovi]]: A tutorial for psychology students and other beginners. (Version 0.7). DOI: 10.24384/hgc3-7p15

The book is released under a [[https://creativecommons.org/licenses/by-sa/4.0/][Creative Commons CC BY-SA 4.0 license]]. This means that this book can be reused, remixed, retained, revised and redistributed (including commercially) as long as appropriate credit is given to the authors. If you remix, or modify the original version of this open textbook, you must redistribute all versions of this open textbook under the same license as the original.


#+HTML: <br><br><br><br>
